version: "3.9"
services:
  service:
    build:
      context: .
      dockerfile: apps/learn_elixir_final/Dockerfile
    environment:
      RELEASE_COOKIE: "secret_cookie"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/learn_elixir_final_pg_prod
      SECRET_KEY_BASE: ixIrw6yknrGn9VqwuV6CGAoAukYM0f7fVxlP64Ghw5fvPfFOhoI9OuKzPo6ylv1H
      RELEASE_NODE: "learn_elixir_final"
    hostname: service
    depends_on:
      - db
    networks:
      - elixirnet

  web:
    build:
      context: .
      dockerfile: apps/learn_elixir_final_web/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/learn_elixir_final_pg_prod
      RELEASE_COOKIE: "secret_cookie"
      SECRET_KEY_BASE: ixIrw6yknrGn9VqwuV6CGAoAukYM0f7fVxlP64Ghw5fvPfFOhoI9OuKzPo6ylv1H
      RELEASE_NODE: "learn_elixir_final_web"
    hostname: web
    ports:
      - "4000:4000"
    networks:
      - elixirnet
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_elixir_final_pg_prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - elixirnet
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - elixirnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - elixirnet

volumes:
  postgres-data:
  prometheus_data:
  grafana_data:

networks:
  elixirnet:
    driver: bridge