global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['web:4050']
  
  - job_name: 'service'
    static_configs:
      - targets: ['service:4050']